const languages = { 
  "english" : {
    "languageValue": "en",
    "english": "English",
    "ukrainian": "Ukrainian",
    "russian": "Russian",
    "selectLabel": "Select Language",
    "documentTitle": "Sign In / Sign Up",
    "signIn": "signin",
    "signUp": "signup",
    "loginFacebook": "Login with Facebook",
    "signupFacebook": "Signup with Facebook",
    "signInError": "Wrong username or password",
    "signUpError": "User already exists",
    "verifyError": "Wrong verification code",
    "requestError": "Wrong email or phone",
    "submitButton": "submit",
    "usernameInput": "Email or phone",
    "passwordInput": "Password",
    "checkboxLabel": "I agree with ",
    "privacyPolicyLink": "Privacy Policy",
    "passwordResetLink": "Forgot your password?",
    "reVerifyLink": "Repeat verification",
    "emailAddress": "Email address",
    "phoneNumber": "Phone number",
    "verifyMessage": "Please input verification code from email",
    "verifyInput": "Verification code",
    "passwordRequestInput": "Email or phone",
    "newPasswordInput": "New password",
    "verifySuccessMessage": "Your account has been successfully verified!",
    "passwordSuccessMessage": "Your password has been successfully updated!",
    "reloginMessage": "Please re-login.",
    "nextButton": "next"
  },
  "russian" : {
    "languageValue": "ru",
    "english": "Английский",
    "ukrainian": "Украинский",
    "russian": "Русский",
    "selectLabel": "Выберите язык",
    "documentTitle": "Вход / Регистрация",
    "signIn": "вход",
    "signUp": "регистрация",
    "loginFacebook": "Войти с Facebook",
    "signupFacebook": "Регистрация с Facebook",
    "signInError": "Неправильный логин или пароль",
    "signUpError": "Такой пользователь уже существует",
    "verifyError": "Неправильный код подтверждения",
    "requestError": "Неправильный email или телефон",
    "submitButton": "отправить",
    "usernameInput": "Email или телефон",
    "passwordInput": "Пароль",
    "checkboxLabel": "Я согласен с ",
    "privacyPolicyLink": "Политикой Конфиденциальности",
    "passwordResetLink": "Забыли пароль?",
    "reVerifyLink": "Повторная верификация",
    "emailAddress": "Email",
    "phoneNumber": "Телефон",
    "verifyMessage": "Пожалуйста, введите код подтверждения",
    "verifyInput": "Код подтверждения",
    "passwordRequestInput": "Email или телефон",
    "newPasswordInput": "Новый пароль",
    "verifySuccessMessage": "Ваш аккаунт успешно подтвержден!",
    "passwordSuccessMessage": "Новый пароль создан!",
    "reloginMessage": "Для применения изменений, пожалуйста, перелогиньтесь. ",
    "nextButton": "далее"
  },
  "ukrainian" : {
    "languageValue": "uk",
    "english": "Англійська",
    "ukrainian": "Українська",
    "russian": "Російська",
    "selectLabel": "Виберіть Мову",
    "documentTitle": "Вхід / Реєстрація",
    "signIn": "вхід",
    "signUp": "реєстрація",
    "loginFacebook": "Увійти с Facebook",
    "signupFacebook": "Реєстрація с Facebook",
    "signInError": "Неправильний логін або пароль",
    "signUpError": "Такий користувач вже існує",
    "verifyError": "Неправильний код підтвердження",
    "requestError": "Неправильний email або телефон",
    "submitButton": "надіслати",
    "usernameInput": "Email або телефон",
    "passwordInput": "Пароль",
    "checkboxLabel": "Я згоден з ",
    "privacyPolicyLink": "Політикой Конфіденційності",
    "passwordResetLink": "Забули пароль?",
    "reVerifyLink": "Повторна верiфiкацiя",
    "emailAddress": "Email",
    "phoneNumber": "Телефон",
    "verifyMessage": "Будь ласка, введіть код підтвердження",
    "verifyInput": "Код підтвердження",
    "passwordRequestInput": "Email або телефон",
    "newPasswordInput": "Новий пароль",
    "verifySuccessMessage": "Ваш обліковий запис підтверджено!",
    "passwordSuccessMessage": "Створено новий пароль!",
    "reloginMessage": "Для застосування змін, будь ласка, перелогіньтесь.",
    "nextButton": "далі"
  }
};

export default languages;